# -*- coding: utf-8 -*-
"""My_RL_Coursework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZevFpD9OSYbeAEXaZWFojk1lct5ihrP
"""

import numpy as np
import random
import matplotlib.pyplot as plt # Graphical library
#from sklearn.metrics import mean_squared_error # Mean-squared error function

"""# Coursework 1 :
See pdf for instructions.
"""

# WARNING: fill in these two functions that will be used by the auto-marking script
# [Action required]

def get_CID():
  return "06009527" # Return your CID (add 0 at the beginning to ensure it is 8 digits long)

def get_login():
  return "lb124" # Return your short imperial login

"""## Helper class"""

# This class is used ONLY for graphics
# YOU DO NOT NEED to understand it to work on this coursework

class GraphicsMaze(object):

  def __init__(self, shape, locations, default_reward, obstacle_locs, absorbing_locs, absorbing_rewards, absorbing):

    self.shape = shape
    self.locations = locations
    self.absorbing = absorbing

    # Walls
    self.walls = np.zeros(self.shape)
    for ob in obstacle_locs:
      self.walls[ob] = 20

    # Rewards
    self.rewarders = np.ones(self.shape) * default_reward
    for i, rew in enumerate(absorbing_locs):
      self.rewarders[rew] = 10 if absorbing_rewards[i] > 0 else -10

    # Print the map to show it
    self.paint_maps()

  def paint_maps(self):
    """
    Print the Maze topology (obstacles, absorbing states and rewards)
    input: /
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders)
    plt.show()

  def paint_state(self, state):
    """
    Print one state on the Maze topology (obstacles, absorbing states and rewards)
    input: /
    output: /
    """
    states = np.zeros(self.shape)
    states[state] = 30
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders + states)
    plt.show()

  def draw_deterministic_policy(self, Policy):
    """
    Draw a deterministic policy
    input: Policy {np.array} -- policy to draw (should be an array of values between 0 and 3 (actions))
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders) # Create the graph of the Maze
    for state, action in enumerate(Policy):
      if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any action
        continue
      arrows = [r"$\uparrow$",r"$\rightarrow$", r"$\downarrow$", r"$\leftarrow$"] # List of arrows corresponding to each possible action
      action_arrow = arrows[action] # Take the corresponding action
      location = self.locations[state] # Compute its location on graph
      plt.text(location[1], location[0], action_arrow, ha='center', va='center') # Place it on graph
    plt.show()

  def draw_policy(self, Policy):
    """
    Draw a policy (draw an arrow in the most probable direction)
    input: Policy {np.array} -- policy to draw as probability
    output: /
    """
    deterministic_policy = np.array([np.argmax(Policy[row,:]) for row in range(Policy.shape[0])])
    self.draw_deterministic_policy(deterministic_policy)

  def draw_value(self, Value):
    """
    Draw a policy value
    input: Value {np.array} -- policy values to draw
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders) # Create the graph of the Maze
    for state, value in enumerate(Value):
      if(self.absorbing[0, state]): # If it is an absorbing state, don't plot any value
        continue
      location = self.locations[state] # Compute the value location on graph
      plt.text(location[1], location[0], round(value,2), ha='center', va='center') # Place it on graph
    plt.show()

  def draw_deterministic_policy_grid(self, Policies, title, n_columns, n_lines):
    """
    Draw a grid representing multiple deterministic policies
    input: Policies {np.array of np.array} -- array of policies to draw (each should be an array of values between 0 and 3 (actions))
    output: /
    """
    plt.figure(figsize=(20,8))
    for subplot in range (len(Policies)): # Go through all policies
      ax = plt.subplot(n_columns, n_lines, subplot+1) # Create a subplot for each policy
      ax.imshow(self.walls+self.rewarders) # Create the graph of the Maze
      for state, action in enumerate(Policies[subplot]):
        if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any action
          continue
        arrows = [r"$\uparrow$",r"$\rightarrow$", r"$\downarrow$", r"$\leftarrow$"] # List of arrows corresponding to each possible action
        action_arrow = arrows[action] # Take the corresponding action
        location = self.locations[state] # Compute its location on graph
        plt.text(location[1], location[0], action_arrow, ha='center', va='center') # Place it on graph
      ax.title.set_text(title[subplot]) # Set the title for the graph given as argument
    plt.show()

  def draw_policy_grid(self, Policies, title, n_columns, n_lines):
    """
    Draw a grid representing multiple policies (draw an arrow in the most probable direction)
    input: Policy {np.array} -- array of policies to draw as probability
    output: /
    """
    deterministic_policies = np.array([[np.argmax(Policy[row,:]) for row in range(Policy.shape[0])] for Policy in Policies])
    self.draw_deterministic_policy_grid(deterministic_policies, title, n_columns, n_lines)

  def draw_value_grid(self, Values, title, n_columns, n_lines):
    """
    Draw a grid representing multiple policy values
    input: Values {np.array of np.array} -- array of policy values to draw
    output: /
    """
    plt.figure(figsize=(20,8))
    for subplot in range (len(Values)): # Go through all values
      ax = plt.subplot(n_columns, n_lines, subplot+1) # Create a subplot for each value
      ax.imshow(self.walls+self.rewarders) # Create the graph of the Maze
      for state, value in enumerate(Values[subplot]):
        if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any value
          continue
        location = self.locations[state] # Compute the value location on graph
        plt.text(location[1], location[0], round(value,1), ha='center', va='center') # Place it on graph
      ax.title.set_text(title[subplot]) # Set the title for the graoh given as argument
    plt.show()

"""## Maze class"""

# This class define the Maze environment

class Maze(object):

  # [Action required]
  def __init__(self):
    """
    Maze initialisation.
    input: /
    output: /
    """
    # self._prob_success = 0.94 # float
    # self._gamma = 0.84 # float
    # self._goal = 3

    # [Action required]
    # Properties set from the CID
    CID = get_CID()
    y = float(CID[-2])
    z = float(CID[-1])
    self._prob_success = 0.8 + 0.02*(9.0 - y) # float
    self._gamma = 0.8 + 0.02 * y # float
    self._goal = int(z % 4) # integer (0 for R0, 1 for R1, 2 for R2, 3 for R3)

    # Build the maze
    self._build_maze()


  # Functions used to build the Maze environment
  # You DO NOT NEED to modify them
  def _build_maze(self):
    """
    Maze initialisation.
    input: /
    output: /
    """

    # Properties of the maze
    self._shape = (13, 10)
    self._obstacle_locs = [
                          (1,0), (1,1), (1,2), (1,3), (1,4), (1,7), (1,8), (1,9), \
                          (2,1), (2,2), (2,3), (2,7), \
                          (3,1), (3,2), (3,3), (3,7), \
                          (4,1), (4,7), \
                          (5,1), (5,7), \
                          (6,5), (6,6), (6,7), \
                          (8,0), \
                          (9,0), (9,1), (9,2), (9,6), (9,7), (9,8), (9,9), \
                          (10,0)
                         ] # Location of obstacles
    self._absorbing_locs = [(2,0), (2,9), (10,1), (12,9)] # Location of absorbing states
    self._absorbing_rewards = [ (500 if (i == self._goal) else -50) for i in range (4) ]
    self._starting_locs = [(0,0), (0,1), (0,2), (0,3), (0,4), (0,5), (0,6), (0,7), (0,8), (0,9)] #Reward of absorbing states
    self._default_reward = -1 # Reward for each action performs in the environment
    self._max_t = 500 # Max number of steps in the environment

    # Actions
    self._action_size = 4
    self._direction_names = ['N','E','S','W'] # Direction 0 is 'N', 1 is 'E' and so on

    # States
    self._locations = []
    for i in range (self._shape[0]):
      for j in range (self._shape[1]):
        loc = (i,j)
        # Adding the state to locations if it is no obstacle
        if self._is_location(loc):
          self._locations.append(loc)
    self._state_size = len(self._locations)

    # Neighbours - each line is a state, ranked by state-number, each column is a direction (N, E, S, W)
    self._neighbours = np.zeros((self._state_size, 4))

    for state in range(self._state_size):
      loc = self._get_loc_from_state(state)

      # North
      neighbour = (loc[0]-1, loc[1]) # North neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('N')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('N')] = state

      # East
      neighbour = (loc[0], loc[1]+1) # East neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('E')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('E')] = state

      # South
      neighbour = (loc[0]+1, loc[1]) # South neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('S')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('S')] = state

      # West
      neighbour = (loc[0], loc[1]-1) # West neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('W')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('W')] = state

    # Absorbing
    self._absorbing = np.zeros((1, self._state_size))
    for a in self._absorbing_locs:
      absorbing_state = self._get_state_from_loc(a)
      self._absorbing[0, absorbing_state] = 1

    # Transition matrix
    self._T = np.zeros((self._state_size, self._state_size, self._action_size)) # Empty matrix of domension S*S*A
    for action in range(self._action_size):
      for outcome in range(4): # For each direction (N, E, S, W)
        # The agent has prob_success probability to go in the correct direction
        if action == outcome:
          prob = 1 - 3.0 * ((1.0 - self._prob_success) / 3.0) # (theoritically equal to self.prob_success but avoid rounding error and garanty a sum of 1)
        # Equal probability to go into one of the other directions
        else:
          prob = (1.0 - self._prob_success) / 3.0

        # Write this probability in the transition matrix
        for prior_state in range(self._state_size):
          # If absorbing state, probability of 0 to go to any other states
          if not self._absorbing[0, prior_state]:
            post_state = self._neighbours[prior_state, outcome] # Post state number
            post_state = int(post_state) # Transform in integer to avoid error
            self._T[prior_state, post_state, action] += prob

    # Reward matrix
    self._R = np.ones((self._state_size, self._state_size, self._action_size)) # Matrix filled with 1
    self._R = self._default_reward * self._R # Set default_reward everywhere
    for i in range(len(self._absorbing_rewards)): # Set absorbing states rewards
      post_state = self._get_state_from_loc(self._absorbing_locs[i])
      self._R[:,post_state,:] = self._absorbing_rewards[i]

    # Creating the graphical Maze world
    self._graphics = GraphicsMaze(self._shape, self._locations, self._default_reward, self._obstacle_locs, self._absorbing_locs, self._absorbing_rewards, self._absorbing)

    # Reset the environment
    self.reset()


  def _is_location(self, loc):
    """
    Is the location a valid state (not out of Maze and not an obstacle)
    input: loc {tuple} -- location of the state
    output: _ {bool} -- is the location a valid state
    """
    if (loc[0] < 0 or loc[1] < 0 or loc[0] > self._shape[0]-1 or loc[1] > self._shape[1]-1):
      return False
    elif (loc in self._obstacle_locs):
      return False
    else:
      return True


  def _get_state_from_loc(self, loc):
    """
    Get the state number corresponding to a given location
    input: loc {tuple} -- location of the state
    output: index {int} -- corresponding state number
    """
    return self._locations.index(tuple(loc))


  def _get_loc_from_state(self, state):
    """
    Get the state number corresponding to a given location
    input: index {int} -- state number
    output: loc {tuple} -- corresponding location
    """
    return self._locations[state]

  # Getter functions used only for DP agents
  # You DO NOT NEED to modify them
  def get_T(self):
    return self._T

  def get_R(self):
    return self._R

  def get_absorbing(self):
    return self._absorbing

  # Getter functions used for DP, MC and TD agents
  # You DO NOT NEED to modify them
  def get_graphics(self):
    return self._graphics

  def get_action_size(self):
    return self._action_size

  def get_state_size(self):
    return self._state_size

  def get_gamma(self):
    return self._gamma

  # Functions used to perform episodes in the Maze environment
  def reset(self):
    """
    Reset the environment state to one of the possible starting states
    input: /
    output:
      - t {int} -- current timestep
      - state {int} -- current state of the envionment
      - reward {int} -- current reward
      - done {bool} -- True if reach a terminal state / 0 otherwise
    """
    self._t = 0
    self._state = self._get_state_from_loc(self._starting_locs[random.randrange(len(self._starting_locs))])
    self._reward = 0
    self._done = False
    return self._t, self._state, self._reward, self._done

  def step(self, action):
    """
    Perform an action in the environment
    input: action {int} -- action to perform
    output:
      - t {int} -- current timestep
      - state {int} -- current state of the envionment
      - reward {int} -- current reward
      - done {bool} -- True if reach a terminal state / 0 otherwise
    """

    # If environment already finished, print an error
    if self._done or self._absorbing[0, self._state]:
      print("Please reset the environment")
      return self._t, self._state, self._reward, self._done

    # Drawing a random number used for probaility of next state
    probability_success = random.uniform(0,1)

    # Look for the first possible next states (so get a reachable state even if probability_success = 0)
    new_state = 0
    while self._T[self._state, new_state, action] == 0:
      new_state += 1
    assert self._T[self._state, new_state, action] != 0, "Selected initial state should be probability 0, something might be wrong in the environment."

    # Find the first state for which probability of occurence matches the random value
    total_probability = self._T[self._state, new_state, action]
    while (total_probability < probability_success) and (new_state < self._state_size-1):
     new_state += 1
     total_probability += self._T[self._state, new_state, action]
    assert self._T[self._state, new_state, action] != 0, "Selected state should be probability 0, something might be wrong in the environment."

    # Setting new t, state, reward and done
    self._t += 1
    self._reward = self._R[self._state, new_state, action]
    self._done = self._absorbing[0, new_state] or self._t > self._max_t
    self._state = new_state
    return self._t, self._state, self._reward, self._done

"""## DP Agent"""

# This class define the Dynamic Programing agent

class DP_agent(object):

  def policy_evaluation(self, V, policy, T, R, absorbing, state_size, action_size, gamma, threshold = 0.0001):
    """
    Policy evaluation on GridWorld
    input:
      - policy {np.array} -- policy to evaluate
      - threshold {float} -- threshold value used to stop the policy evaluation algorithm
      - gamma {float} -- discount factor
    output:
      - V {np.array} -- value function corresponding to the policy
    """

    # Ensure inputs are valid
    assert (policy.shape[0] == state_size) and (policy.shape[1] == action_size), "The dimensions of the policy are not valid."
    assert (gamma <=1) and (gamma >= 0), "Discount factor should be in [0, 1]."

    # Initialisation
    delta = 2*threshold # Ensure delta is bigger than the threshold to start the loop
    V = np.zeros(state_size)
    Vnew = np.copy(V)
    while delta > threshold:
      for s in range(state_size):
        if not absorbing[0, s]:
          Vnew[s] = np.sum([policy[s][a]*np.sum([(T[s][s_prime][a]*(R[s][s_prime][a] + gamma*V[s_prime])) for s_prime in range(state_size)]) for a in range(action_size)])
      delta =  max(abs(Vnew - V))
      # Update V
      V = np.copy(Vnew)
    return V

  # [Action required]
  # WARNING: make sure this function can be called by the auto-marking script
  def solve(self, env):
    """
    Solve a given Maze environment using Dynamic Programming
    input: env {Maze object} -- Maze to solve
    output:
      - policy {np.array} -- Optimal policy found to solve the given Maze environment
      - V {np.array} -- Corresponding value function
    """

    # Initialisation (can be edited)
    policy = np.zeros((env.get_state_size(), env.get_action_size()))
    policy[:, 0] = 1 # Initialise policy to choose action 1 systematically
    V = np.zeros(env.get_state_size())
    T = env.get_T()
    R = env.get_R()
    absorbing = env.get_absorbing()
    state_size = env.get_state_size()
    action_size = env.get_action_size()
    gamma = env.get_gamma()
    ####
    # Add your code here
    # WARNING: for this agent only, you are allowed to access env.get_T(), env.get_R() and env.get_absorbing()
    ####
    policy_stable = False # Condition to stop the main loop
    while not policy_stable:
      policy_stable = True
      V = self.policy_evaluation(V, policy, T, R, absorbing, state_size, action_size, gamma)
      for s in range(state_size):
        if not absorbing[0, s]: # Ensure state are non-absorbing

          b = np.argmax(policy[s, :])
          action_values = np.zeros(action_size)

          for a in range(action_size):
            action_values[a] = np.sum([(T[s][s_prime][a]*(R[s][s_prime][a] + gamma*V[s_prime])) for s_prime in range(state_size)])
          best_action = np.argmax(action_values)
          if b != best_action:
            policy_stable = False
            policy[s, :] = [1 if i==best_action else 0 for i in range(action_size)]

    return policy, V

"""## MC agent"""

# This class define the Monte-Carlo agent

class MC_agent(object):

  def get_trace(self, env, policy, start_state):
    trace = []
    done = False
    state = start_state
    sum_of_rewards = 0

    while not done:
        action = np.random.choice(env.get_action_size(), p=policy[state])
        _, next_state, reward, done = env.step(action)
        sum_of_rewards += reward
        trace.append((state, action, reward))
        state = next_state

    return trace, sum_of_rewards

  # [Action required]
  # WARNING: make sure this function can be called by the auto-marking script
  def solve(self, env):
    """
    Solve a given Maze environment using Monte Carlo learning
    input: env {Maze object} -- Maze to solve
    output:
      - policy {np.array} -- Optimal policy found to solve the given Maze environment
      - values {list of np.array} -- List of successive value functions for each episode
      - total_rewards {list of float} -- Corresponding list of successive total non-discounted sum of reward for each episode
    """

    # Initialisation (can be edited)
    Q = np.random.rand(env.get_state_size(), env.get_action_size())
    V = np.zeros(env.get_state_size())
    values = [V]
    total_rewards = []

    ####
    # Add your code here
    # WARNING: this agent only has access to env.reset() and env.step()
    # You should not use env.get_T(), env.get_R() or env.get_absorbing() to compute any value
    ####
    gamma = env.get_gamma()
    num_episodes = 2000
    epsilon = 0.4

    policy = np.ones((env.get_state_size(), env.get_action_size())) * (1.0/env.get_action_size())
    Returns = { (s, a): [] for s in range(env.get_state_size()) for a in range(env.get_action_size()) }

    for i in range(num_episodes):
      _, start_state, _, _ = env.reset()
      trace, sum_of_rewards = self.get_trace(env, policy, start_state)
      total_rewards.append(sum_of_rewards)

      G = 0
      for step in range(len(trace)-1, -1, -1):
        s,a,r = trace[step]
        G = gamma*G + r
        if (s,a) not in [(s_a[0], s_a[1]) for s_a in trace[:step]]:
          Returns[(s,a)].append(G)
          Q[s,a] = np.mean(Returns[(s,a)])
          a_star = np.argmax(Q[s])
          for a in range(env.get_action_size()):
            if a == a_star:
              policy[s, a] = 1 - epsilon + (epsilon/env.get_action_size())
            else:
              policy[s, a] = epsilon/env.get_action_size()

      V = np.max(Q, axis=1)
      values.append(V.copy())

    return policy, values, total_rewards

  def solveforplot(self, env, epsilon):

    Q = np.random.rand(env.get_state_size(), env.get_action_size())
    V = np.zeros(env.get_state_size())
    values = [V]
    total_rewards = []
    gamma = env.get_gamma()
    num_episodes = 2000

    policy = np.ones((env.get_state_size(), env.get_action_size())) * (1.0/env.get_action_size())
    Returns = { (s, a): [] for s in range(env.get_state_size()) for a in range(env.get_action_size()) }

    for i in range(num_episodes):
      _, start_state, _, _ = env.reset()
      trace, sum_of_rewards = self.get_trace(env, policy, start_state)
      total_rewards.append(sum_of_rewards)

      G = 0
      for step in range(len(trace)-1, -1, -1):
        s,a,r = trace[step]
        G = gamma*G + r
        if (s,a) not in [(s_a[0], s_a[1]) for s_a in trace[:step]]:
          Returns[(s,a)].append(G)
          Q[s,a] = np.mean(Returns[(s,a)])
          a_star = np.argmax(Q[s])
          for a in range(env.get_action_size()):
            if a == a_star:
              policy[s, a] = 1 - epsilon + (epsilon/env.get_action_size())
            else:
              policy[s, a] = epsilon/env.get_action_size()

      V = np.max(Q, axis=1)
      values.append(V.copy())

    return policy, values, total_rewards


"""## TD agent"""

# This class define the Temporal-Difference agent

class TD_agent(object):

  # [Action required]
  # WARNING: make sure this function can be called by the auto-marking script
  def solve(self, env):
    """
    Solve a given Maze environment using Temporal Difference learning
    input: env {Maze object} -- Maze to solve
    output:
      - policy {np.array} -- Optimal policy found to solve the given Maze environment
      - values {list of np.array} -- List of successive value functions for each episode
      - total_rewards {list of float} -- Corresponding list of successive total non-discounted sum of reward for each episode
    """

    # Initialisation (can be edited)
    Q = np.random.rand(env.get_state_size(), env.get_action_size())
    V = np.zeros(env.get_state_size())
    policy = np.zeros((env.get_state_size(), env.get_action_size()))
    values = [V]
    total_rewards = []

    ####
    # Add your code here
    # WARNING: this agent only has access to env.reset() and env.step()
    # You should not use env.get_T(), env.get_R() or env.get_absorbing() to compute any value
    ####

    gamma = env.get_gamma()
    num_episodes = 800
    complete = False
    alpha = 0.5
    epsilon = 0.2

    for i in range(num_episodes):
      _, start_state, _, _ = env.reset()

      trace = []
      done = False
      state = start_state
      sum_of_rewards = 0

      while not done:
        random = np.random.rand()

        if random < epsilon:
          action = np.random.choice(env.get_action_size())
        else:
          action = np.argmax(Q[state])

        t, next_state, reward, done = env.step(action)
        sum_of_rewards += reward
        # trace.append((t-1, state, action, reward))
        best_action = np.argmax(Q[next_state])
        Q[state, action] = Q[state, action] + alpha*(reward + gamma*Q[next_state, best_action] - Q[state, action])
        state = next_state
      total_rewards.append(sum_of_rewards)

    V = np.max(Q, axis=1)
    values.append(V.copy())

    for s in range(env.get_state_size()):
      best_action = np.argmax(Q[s])
      policy[s, :] = [1 if a==best_action else 0 for a in range(env.get_action_size())]

    return policy, values, total_rewards

  def solveforplot(self, env, ep, al):

      # Initialisation (can be edited)
      Q = np.random.rand(env.get_state_size(), env.get_action_size()) #I changed this
      V = np.zeros(env.get_state_size())
      policy = np.zeros((env.get_state_size(), env.get_action_size()))
      values = [V]
      total_rewards = []

      ####
      # Add your code here
      # WARNING: this agent only has access to env.reset() and env.step()
      # You should not use env.get_T(), env.get_R() or env.get_absorbing() to compute any value
      ####
      gamma = env.get_gamma()
      num_episodes = 800
      complete = False
      alpha = al
      epsilon = ep

      for i in range(num_episodes):
        _, start_state, _, _ = env.reset()

        trace = []
        done = False
        state = start_state
        sum_of_rewards = 0

        while not done:
          random = np.random.rand()

          if random < epsilon:
            action = np.random.choice(env.get_action_size())
          else:
            action = np.argmax(Q[state])

          t, next_state, reward, done = env.step(action)
          sum_of_rewards += reward
          # trace.append((t-1, state, action, reward))
          best_action = np.argmax(Q[next_state])
          Q[state, action] = Q[state, action] + alpha*(reward + gamma*Q[next_state, best_action] - Q[state, action])
          state = next_state
        total_rewards.append(sum_of_rewards)

      V = np.max(Q, axis=1)
      values.append(V.copy())

      for s in range(env.get_state_size()):
        best_action = np.argmax(Q[s])
        policy[s, :] = [1 if a==best_action else 0 for a in range(env.get_action_size())]

      return policy, values, total_rewards